FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y openssh-server sudo python3 python3-apt curl && \
    mkdir -p /var/run/sshd && \
    useradd -rm -d /home/ansible -s /bin/bash -g root -G sudo -u 1000 ansible && \
    echo 'ansible:ansible' | chpasswd && \
    echo 'ansible ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

EXPOSE 22 8083

CMD ["/usr/sbin/sshd", "-D"]
