FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y ansible openssh-client sshpass curl && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /ansible

ENTRYPOINT ["ansible-playbook"]
